name: liczby_slownie
description: A small library for translating numbers into polish words.
version: 1.0.0
publish_to: https://pub.dev/
homepage: https://github.com/UnnamedXAer/dart-liczby-slownie#readme

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
