name: liczby_slownie
description: liczby_slownie is a library for translating numbers and prices into polish words.
version: 1.0.1
repository: https://github.com/UnnamedXAer/dart-liczby-slownie
issue_tracker: https://github.com/UnnamedXAer/dart-liczby-slownie/issues
homepage: https://github.com/UnnamedXAer/dart-liczby-slownie#readme

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
